### ISSUE TITLE
Automatic slide when new post with specific tag or category is added

### ISSUE THREAD

**Issue by fbosman** [mennolui/wp-foyer#17]
Hi,

Is it possible to have an automatic slide when a new post with a specific tag or category is added? We currently use a rss feed as source for our signage but we would like to reduce the number of applications needed.
Regards,
Frans

**Comment by mennolui** [comment]
Hoi Frans!

Thanks for the input.

A slide that creates a slide for each of the latest X posts (of a category or tag) is on my roadmap.
But your idea sounds a but different, since you only want it to display a slide when a post is _new_. Can you define when a post is _new_?

Menno

**Comment by fbosman** [comment]
Hi Menno,

I think we try to get the same.

The requirement I have: Posts with a special category or tag should display on a screen including the featured image. The order should be the date of last edit of the post in reverse order.
It should be possible to set a maximum on the number of posts or a timeframe (last week, last month, last day) with the number of weeks/months/days.
The category or tag should designate the channel to use.

I stated my request as a solution but should have stated the requirement...

Regards.

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 15 mrt. 2018 om 20:56 heeft Menno Luitjes <notifications@github.com> het volgende geschreven:

Hoi Frans!

Thanks for the input.

A slide that creates a slide for each of the latest X posts (of a category or tag) is on my roadmap.
But your idea sounds a but different, since you only want it to display a slide when a post is new. Can you define when a post is new?

Menno

**Comment by mennolui** [comment]
Yes, that sounds roughly like what I had in mind :-) And I like the 'show posts of last X days' option, in addition to 'show last X posts'.

Would you really like to order by last edit, and why, or do you mean date published (which can always be updated in WordPress if you'd like)?

**Comment by fbosman** [comment]
I think the publish date should do it as we indeed can control that one. Not always an edities post has the same status as a new post.

**Comment by l0calhost** [comment]
:+1: for date published. :)

**Comment by mennolui** [comment]
Hey @fbosman and @l0calhost, just released a Recent Posts slide format in Foyer version 1.7.1. Real world testing and feedback are appreciated!

**Comment by l0calhost** [comment]
Hey @mennolui, thanks for your work, looks good so far! One idea that crossed my mind while testing: For posts with more text it would be great to have more space to use. That might be achieved by using the post entry image as the background image and using the space on the left for the entry text.
