### ISSUE TITLE
Add shortcode support.

### ISSUE THREAD

**Issue by l0calhost** [mennolui/wp-foyer#24]
Hi Menno, 

first of all, thanks for your great work! This is the first wordpress plugin that actually does what it says. :)

As an enhancement, i really would like to see shortcode support for the "text" slide. This way, it would be easily possible to add dynamic content like upcoming event listings or recently added gallery images. #

**Comment by mennolui** [comment]
Sounds interesting :-)

The Text slide is currently designed to work well with text. For example the width of the content area is limited for readability and it has a translucent background. Would it work for you if we would display a shortcode within that content area? Otherwise could you upload a mock-up of how you would present it?

**Comment by l0calhost** [comment]
Yes, it would perfectly work this way! My idea is to present the following training lessons (depends on day of the week) and upcoming (read: future) events. At the moment, i maintain these entries with the "Events Manager" plugin, which gives me very powerful shortcodes to present events the way i need. 

Example: By adding the following code 
```
<ul>
[events_list category="152" scope="future" limit="6"]<li>#_EVENTDATES, #_LOCATIONTOWN: #_EVENTLINK</li>[/events_list]
</ul>
```
to a page or post, i get an unordered list with list items styled as defined. If text slides would support this, i, for this case, would expect it to look something like: 
![example](https://user-images.githubusercontent.com/8111901/38666161-97239a3a-3e3e-11e8-8c9e-2c99175eeffa.jpg)

This way, i can have a single text slide with self-updating content. :)

**Comment by l0calhost** [comment]
Hi @mennolui, i've been further investigating into shortcodes. You can also use them for embedding whole image galleries into pages / posts, which might make an implementation in foyer quite complex. ;) I don't want to make things overly complicated, i can achieve what i need with pages, a custom page template and the "external url" slide. This issue can be closed.
