### ISSUE TITLE
Add Page slide format

### ISSUE THREAD

**Issue by l0calhost** [mennolui/wp-foyer#25]
Hi again. :)

Is it possible to not only add recent posts, but also pages?

**Comment by mennolui** [comment]
Hi there!,

What would a Page slide look like? Same as a Post slide but without the date — title, content, featured image? And I’m curious in what scenario you would use Page slides, and why not set up some Text slides?

Thanks

**Comment by l0calhost** [comment]
Actually, yes, just like a post slide with title, content and featured image. I'd like to use it for our sports club, we have a display in our rooms that should show recent posts and upcoming events, but also give info to more static content like different sport styles, our trainer team etc. 

You're right, it would surely be possible to achieve this with text slides. But this way content is doubled, as is the maintanance.

**Comment by mennolui** [comment]
Thanks for elaborating, I understand the benefits. When I find the time I will probably add this to the plugin.

One practical question though: Do you expect the average amount of page content (or the excerpt) will fit on a slide, as it is designed now?

**Comment by l0calhost** [comment]
Thanks a lot! 

Let me answer the question lawyer-style: it depends. ;)  There sure are long texts not suitable for a digital signage presentation, but i definitely have some content that would fit. Besides, is it possible to scale text / image size to match the screen?

Another tought about using pages was to use it to prepare dynamic content with short codes ( like mentioned in #24 ).

**Comment by mennolui** [comment]
Page slide format was added, some months ago!
