### ISSUE TITLE
Add Rich Text on slides text content

### ISSUE THREAD

**Issue by brunabites** [mennolui/wp-foyer#36]
Hi Menno.

Is it possible to add rich text options to "Content" field in Text Slides, so we can add some bold, italic or even tables? For instance I need a table to show a table of events and dates....

BTW Great plugin! 👍

**Comment by mennolui** [comment]
Hey Bruna, thanks!

It is already possible to add HTML to the Content field of the Text slide. However there is no WYSIWYG buttons to easily create that HTML. I might add that, or Gutenberg editor support, at some point in a future release.

**Comment by brunabites** [comment]
Great! I've noticed that i can add html. But since the content editor is not me, it might be a little difficult to do so. But I'm glad to hear you intend to do it....
