### ISSUE TITLE
Auto refresh when channel is updated

### ISSUE THREAD

**Issue by JeejD** [mennolui/wp-foyer#37]
Hi Menno,

Is it possible to make the channel auto refresh when it is updated without refreshing the browser it runs on? I tried some AJAX plugins but this didn't do the job.

May thanks. Kepp up the good work!

regards,

**Comment by mennolui** [comment]
No need! The display refreshes every 5 minutes, if needed. Check out the plugin FAQ for exact details about refreshing: https://nl.wordpress.org/plugins/foyer/

Does that answer your question?

Best,
Menno
