### ISSUE TITLE
Compatibility with Custom Post Types + ACF

### ISSUE THREAD

**Issue by JeejD** [mennolui/wp-foyer#38]
Hi Menno,

Is there any way it would be possible to be enable to choose from custom post types when selecting a slide type? Adding the Custom Post Types in the dropdown menu when adding a new slide would be an awesome option.

Thank you for all your time.

**Comment by mennolui** [comment]
Hi! I guess you would first choose from a list of Custom Post Types, and then a post from a list of all posts for that Custom Post Type. But what would the slide then display? The title and the content (or excerpt), just like the 'Post' slide format? Or would it display a single page from the website, just like the 'External web page' slide format?

**Comment by JeejD** [comment]
If you combine custom post types with Advanced custom field you can make some pretty cool pages. I guess it would be displayed as the post option foe Foyer.

Or am i the only one that sees some poyential here? 😜😂

**Comment by JeejD** [comment]
Hi Menno,

After thinking some more about this, i think the conclusion is that CPT+ ACF does not bring any real new features to the Foyer plugin. Thank you.

**Comment by mennolui** [comment]
Thanks for letting me know. Something like a 'Page' slide format is already on my list so I'll close this one.
