### ISSUE TITLE
Would this work on raspberry pi?

### ISSUE THREAD

**Issue by quintendewilde** [mennolui/wp-foyer#40]
Hi,

I could not find this anywhere. 

Build could this work on a raspberry pi ? This would solve our digital signage problems.

Kindest regards

**Comment by JeejD** [comment]
Quinten, if you run android on rasberry pi and install an use the Fully kiosk broswer app you can set it up easily. Just point the app to your wp installation and make the app run as a startup app.

**Comment by JeejD** [comment]
Even better: point the app directly to your foyer screen and voila 👌

**Comment by quintendewilde** [comment]
Ok promising. One little thing :) How do I get the wordpress running online (without the raspberry for the moment) 

I'm unable to get any slide visible when I visit the page.
Or am I not getting the fundamentals wrong of the wordpress plugin

**Comment by mennolui** [comment]
Hi @quintendewilde, check out this FAQ about Foyer and the Raspberry Pi (although, based on a regular Linux OS, not Android): 
https://wordpress.org/plugins/foyer/#can%20i%20use%20a%20raspberry%20pi%20mini-computer%20for%20my%20digital%20sign%3F

About the WordPress side of things: Did you manage to install WordPress, install Foyer, and add some slides? Did you add them to a channel, and that channel to a display? You should then view that display URL in the browser of you digital signage device (the Pi), or any other browser where you are not logged in to WordPress.

@JeejD Android on Pi sounds interesting. Could you point me to install instructions that I could share with other users? How is the visual performance? Are fade and slide transitions between slides smooth? And what about MP4 videos, and YouTube videos? 

Best,
Menno

**Comment by JeejD** [comment]
@quintendewilde I would say it works the same as on a laptop. Please a DC ice my previous answer to Menno about working with Foyer on a Andrid mediabox. That's the only experience i have.

**Comment by quintendewilde** [comment]
@JeejD Android on Raspberry Pi = Lineage OS of Konstakang? Thanks for all the help people.

**Comment by JeejD** [comment]
@quintendewilde unfortunately I don't that kind of knowledge of Raspberry Pi.

**Comment by Amosar** [comment]
If it can still help you or help future visitor I use stock raspbian to do that and I've just modified ``~/.config/lxsession/LXDE-pi/autostart`` with that :
```
#Disable screen saving
@xset s off
@xset -dpms
@xset s noblank
#use chromium in full screen
@chromium-browser --kiosk --incognito --app=http://url
```
This will start chromium in fullscreen with the url that you specified. if you want to access to the desktop, you need to do CTRL+ALT+T and then launch it

**Comment by boschkundendienst** [comment]
> Hi,
> 
> I could not find this anywhere.
> 
> Build could this work on a raspberry pi ? This would solve our digital signage problems.
> 
> Kindest regards

I did exactly that, checkout https://github.com/boschkundendienst/raspisignage

DS-client and Server (WP + Foyer + Theater) on a Pi. Works on Pi3 and Pi4. For videos in the slides you should definitely go with a Pi4.
