### ISSUE TITLE
Digital Signage Demo with Foyer

### ISSUE THREAD

**Issue by JeejD** [mennolui/wp-foyer#45]
Hi Menno, I promised you a little example of how I used your plugin. Some of my customers were looking for a custom solution, so I made one.

Once again, thanks to everone who helped building the Foyer plugin to what it is now. Especially you Menno.

Please check out my usage of the Foyer plugin at

https://localwallwebapp.nl/users/demo

Username: demo
Password: demo

**Comment by mennolui** [comment]
Looks good! Foyer-as-a-service :-)
I imagine this will be perfect for those not managing a WordPress website and instead are just looking for easy to use digital signage. Would be interesting te hear how this unfolds, if you like!

Best,
Menno

https://foyer.tv/
https://www.instagram.com/foyer.tv/
