### ISSUE TITLE
Make templates extendable

### ISSUE THREAD

**Issue by krafit** [mennolui/wp-foyer#48]
I really love how Foyer allows us to control our digital signage from a familiar (WP) backend. There are however some cases in wich I'd love to be able to customizer the very structure of the template files.

I'd love to be able to copy the whole `/public/templates/` directory (or parts) to my (child)theme for further customization. WooCommerce for example handles templates just like that.

**Comment by mennolui** [comment]
This is possible, Foyer supports templating override within your own theme like WooCommerce does!

You've maybe already found this, but if not check out this FAQ:
https://wordpress.org/plugins/foyer/#can%20i%20change%20the%20template%20of%20a%20slide%20format%3F

This might also interest you as a developer:
https://wordpress.org/plugins/foyer/#can%20i%20add%20my%20own%20slide%20formats%3F
