### ISSUE TITLE
As promised, the tutorial for Wordpress X Foyer

### ISSUE THREAD

**Issue by JeejD** [mennolui/wp-foyer#55]
Hi Menno,

Just here to let you know that I made you a promise a while back about a tutorial I would do on the Foyer plugin.

I want to let you know that I've recently published a full tutorial on how to make a full digital signage application with your Foyer plugin. (much love!)

You can find the tutorial here:
https://wpboulevard.com/how-to-build-wordpress-digital-signage-application/

Thanks for everything!

**Comment by mennolui** [comment]
Thanks @JeejD ! It's an easy read. Any feedback from readers yet?

I have one question, about this part you wrote..

> In this tutorial we will be using the plugin in a full screen view only so we don’t need any additional setup. As the plugin is not full screen by default, this is where the script files come in we talked about in the Introduction.

What do you mean by 'not full screen by default'? And what did you change / add to the three PHP files in your zip? Just curious, maybe you made an improvement that I like and can add to my list of feature requests. Generally speaking I would say it's not necessary to change the plugin files.

Groeten!
Menno

**Comment by JeejD** [comment]
Well as far as I know your plugin is not full screen by default. Please correct me if I'm wrong. So, in order to get full screen video/content slides with every theme I adjusted the files mentioned in the tutorial. 😁

**Comment by JeejD** [comment]
So, I only tweaked those three(?) files from the tutorial to get full screen mode on every device.

**Comment by mennolui** [comment]
Ha, live chat ;-)

Foyer displays/slides should completely fill the browser viewport by default. For example this demo:
http://demo.foyer.tv/

Don't you see that presentation as full screen? After switching your browser to full screen mode of course..

**Comment by JeejD** [comment]
Menno,

I'm not sure where it went wrong, but it seems you are indeed correct. The only difference now when I compare your code with my adjusted code is that the full screen mode is also eneabled when a user is logged in and watching the Display URL.

Is it correct that when a user is logged in and previews the display URL, that it is not in full screen?

I will have to correct my tutorial. My apologies.

**Comment by escoand** [comment]
About the logged in user and full screen:
Yes, this was also my experience.

**Comment by JeejD** [comment]
So, aparently this is theme related. Menno, is there a way to have the previews full screen aswel, only then with the landscape/vertical bar?
