### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by gabriellluz** [mennolui/wp-foyer#7]
Hi, great idea. 

iframe support is highly suggested. Thanks for your efforts. If you need suggestions, I actually work with Digital Signage for the government.

**Comment by mennolui** [comment]
Hey, thanks!

I just released a new version of the plugin introducing iframe support.

For your purpose does it need some sort of scaling feature? Many regular websites max out at a certain width, eg. 1200 pixels. So when displaying on a 1920 pixels wide screen this would add a lot of whitespace left/right. Is this an issue with the specific pages that you will be including in iframe slides? If so could you send me some examples?

Let me know what you think!

Also, if you have more suggestions I would be happy to hear them. Feel free to open more issues or send me a message at menno@mennoluitjes.nl.

Menno

**Comment by mennolui** [comment]
PS. If you like the plugin, a rating or review is very much appreciated https://wordpress.org/support/plugin/foyer/reviews/ :-)
